### ISSUE TITLE
win整合包0.2 启动api 使用API进行调用时出现服务器500错误

### ISSUE THREAD

**Issue by Dx-hualuo** [jianchang512/sense-api#1]
## 调用方法（Apifox HTTP Post FormData）

![image](https://github.com/user-attachments/assets/6000f0a8-3e81-4d36-a69b-cbb94fb76a49)

## 从启动到结束完整日志

```log
Notice: ffmpeg is not installed. torchaudio is used to load audio
If you want to use ffmpeg backend to load audio, please install it by:
        sudo apt install ffmpeg # ubuntu
        # brew install ffmpeg # mac
D:\senseapi\runtime\./Lib/site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
funasr version: 1.1.12.
2024-11-10 16:38:29,300 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
D:\senseapi\runtime\./Lib/site-packages\funasr\train_utils\load_pretrained_model.py:39: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ori_state = torch.load(path, map_location=map_location)
2024-11-10 16:38:32,887 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\17868\AppData\Local\Temp\jieba.cache
DEBUG:jieba:Loading model from cache C:\Users\17868\AppData\Local\Temp\jieba.cache
Loading model cost 0.269 seconds.
DEBUG:jieba:Loading model cost 0.269 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
funasr version: 1.1.12.
2024-11-10 16:38:48,384 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
funasr version: 1.1.12.
2024-11-10 16:38:49,203 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
2024-11-10 16:38:52,583 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
funasr version: 1.1.12.
2024-11-10 16:39:09,178 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
INFO:     Started server process [32348]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
lang='zh',file.filename='1110-145040_1.1s-seed11.pt-temp0.1-top_p0.701-top_k20-len10-35537-merge.wav'
rtf_avg: 0.029: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.87it/s]
INFO:     127.0.0.1:13564 - "POST /asr HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\senseapi\runtime\./Lib/site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\senseapi\runtime\./Lib/site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "D:\senseapi\runtime\./Lib/site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\senseapi\runtime\./Lib/site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\senseapi\runtime\./Lib/site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "D:\senseapi\runtime\./Lib/site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\senseapi\runtime\..\api.py", line 125, in asr
    chunk.export(filename)
  File "D:\senseapi\runtime\./Lib/site-packages\pydub\audio_segment.py", line 963, in export
    p = subprocess.Popen(conversion_command, stdin=devnull, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by lvsenlin** [comment]
把ffmpeg添加环境变量即可
